### ISSUE TITLE
Fix merge permissions and `CODEOWNERS`

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-isce2#26]
After I approved https://github.com/ASFHyP3/hyp3-isce2/pull/22, I was able to merge but @forrestfwilliams was not.

Also, https://github.com/ASFHyP3/hyp3-isce2/blob/develop/.github/CODEOWNERS contains errors but https://github.com/ASFHyP3/hyp3-gamma/blob/develop/.github/CODEOWNERS does not, even though they appear to be identical.

I don't know if either of these two issues is related, or if the merge permissions issue has anything to do with this setting (which is enabled) from the `main` branch protection rule:

> Restrict who can push to matching branches

**Comment by jhkennedy** [comment]
@jtherrmann looking at the codeowners error, it's likely the repository access hasn't been added to the teams:
![image](https://user-images.githubusercontent.com/7882693/231276154-2bec1443-8bfd-4a81-b05c-32a363bc109d.png)

which you can confirm in the settings:
![image](https://user-images.githubusercontent.com/7882693/231276292-d82be3bc-243b-4bc1-8887-bde70129be55.png)

As for why you could and Forrest couldn't, it's because you're an org owner, and forest is just a member:
![image](https://user-images.githubusercontent.com/7882693/231276557-96b17bf1-d2ef-4cd1-a53c-ba9567b704bc.png)

**Comment by jhkennedy** [comment]
I've made @forrestfwilliams an owner of the org, and I've added the teams:
![image](https://user-images.githubusercontent.com/7882693/231277074-6f782d20-5a11-4d4d-b6c5-ed1567d3a72b.png)

**Comment by jhkennedy** [comment]
@jtherrmann for the branch protection, you just need to let `@ASFHyP3/automation` bypass the requirements

**Comment by jtherrmann** [comment]
@jhkennedy Thank you! 🎉
